version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands: 
      - npm install -g pnpm 
      - pnpm install
  
  build: 
    commands:
      - echo $DATABASE_URL
      - pnpm prisma generate
      - pnpm build 

artifacts: 
  files:
    - '**/*'